-- Ship vitals persisted per owned ship instance.
ALTER TABLE "Ship" ADD COLUMN IF NOT EXISTS "hp" DOUBLE PRECISION NOT NULL DEFAULT 1000;
ALTER TABLE "Ship" ADD COLUMN IF NOT EXISTS "shields" DOUBLE PRECISION NOT NULL DEFAULT 500;
ALTER TABLE "Ship" ADD COLUMN IF NOT EXISTS "maxHp" DOUBLE PRECISION NOT NULL DEFAULT 1000;
ALTER TABLE "Ship" ADD COLUMN IF NOT EXISTS "maxShields" DOUBLE PRECISION NOT NULL DEFAULT 500;
