import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'quick-start',
    'play',
    {
      type: 'category',
      label: 'AsteronEngine',
      link: {
        type: 'generated-index',
        slug: '/editor',
        title: 'AsteronEngine',
        description:
          'The Electron authoring workspace — projects, scenes, prefabs, planets, Play mode, and web builds.',
      },
      items: [{type: 'autogenerated', dirName: 'editor'}],
    },
    {
      type: 'category',
      label: 'Server Console',
      link: {
        type: 'generated-index',
        slug: '/server-console',
        title: 'Server Console',
        description:
          "The editor's Server tab — operator console for the catalog, players, and game settings on the Rust backend.",
      },
      items: [{type: 'autogenerated', dirName: 'server-console'}],
    },
    'assets',
    'roadmap',
    {
      type: 'category',
      label: 'Engineering',
      link: {
        type: 'generated-index',
        slug: '/engineering',
        title: 'Engineering',
        description:
          'Stack, architecture, and design principles behind ClaudeCitizen.',
      },
      items: [{type: 'autogenerated', dirName: 'engineering'}],
    },
  ],
};

export default sidebars;
