import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'quick-start',
    'play',
    'editor',
    'assets',
    'roadmap',
    {
      type: 'category',
      label: 'Engineering',
      link: {
        type: 'generated-index',
        slug: '/engineering',
        title: 'Engineering',
        description:
          'Stack, architecture, and design principles behind ClaudeCitizen.',
      },
      items: [{type: 'autogenerated', dirName: 'engineering'}],
    },
  ],
};

export default sidebars;
