import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'quick-start',
    'play',
    {
      type: 'category',
      label: 'CC Editor',
      link: {
        type: 'generated-index',
        slug: '/cc-editor',
        title: 'CC Editor',
        description:
          'Dev-only world builder and prefab authoring — stations, ships, props, and more.',
      },
      items: [{type: 'autogenerated', dirName: 'cc-editor'}],
    },
    {
      type: 'category',
      label: 'Admin App',
      link: {
        type: 'generated-index',
        slug: '/admin-app',
        title: 'Admin App',
        description:
          'Operator console for game catalog, users, and settings on the Nest.js backend.',
      },
      items: [{type: 'autogenerated', dirName: 'admin-app'}],
    },
    'assets',
    'roadmap',
    {
      type: 'category',
      label: 'Engineering',
      link: {
        type: 'generated-index',
        slug: '/engineering',
        title: 'Engineering',
        description:
          'Stack, architecture, and design principles behind ClaudeCitizen.',
      },
      items: [{type: 'autogenerated', dirName: 'engineering'}],
    },
  ],
};

export default sidebars;
